version: "3.8"

services:
  postgres:
    image: postgres:15
    container_name: secure-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: securedb
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5440:5432"
    networks:
      - secure-net

  secure-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: secure-api
    restart: always
    depends_on:
      - postgres
    env_file: .env
    volumes:
      - .:/app   # ðŸ‘ˆ live code mount for local dev
      - /app/node_modules
    command: npm run start:dev  # ðŸ‘ˆ hot reload inside container
    ports:
      - "3000:3000"
    networks:
      - secure-net

networks:
  secure-net:
    driver: bridge

volumes:
  pgdata:
